-- Controle mensal de aprovação da premiação do PA.
-- A ausência de aprovação mantém a premiação como pendente para a vendedora.

create table if not exists public.aprovacoes_premiacao_pa (
  id bigint generated by default as identity primary key,
  usuario_id uuid not null references public.usuarios_pa(id) on delete cascade,
  mes date not null check (extract(day from mes) = 1),
  status text not null default 'pendente' check (status in ('pendente', 'aprovada', 'reprovada')),
  aprovado_por uuid references public.usuarios_pa(id),
  aprovado_em timestamptz,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (usuario_id, mes)
);

alter table public.aprovacoes_premiacao_pa enable row level security;

drop policy if exists "usuario_pa_le_propria_aprovacao" on public.aprovacoes_premiacao_pa;
create policy "usuario_pa_le_propria_aprovacao"
on public.aprovacoes_premiacao_pa for select to authenticated
using (usuario_id = auth.uid() or public.eh_admin_pa());

drop policy if exists "usuario_pa_cria_aprovacao_pendente" on public.aprovacoes_premiacao_pa;
create policy "usuario_pa_cria_aprovacao_pendente"
on public.aprovacoes_premiacao_pa for insert to authenticated
with check (
  usuario_id = auth.uid()
  and status = 'pendente'
  and aprovado_por is null
  and aprovado_em is null
);

drop policy if exists "admin_pa_cria_aprovacao" on public.aprovacoes_premiacao_pa;
create policy "admin_pa_cria_aprovacao"
on public.aprovacoes_premiacao_pa for insert to authenticated
with check (public.eh_admin_pa());

drop policy if exists "admin_pa_atualiza_aprovacao" on public.aprovacoes_premiacao_pa;
create policy "admin_pa_atualiza_aprovacao"
on public.aprovacoes_premiacao_pa for update to authenticated
using (public.eh_admin_pa())
with check (public.eh_admin_pa());

drop policy if exists "admin_pa_exclui_aprovacao" on public.aprovacoes_premiacao_pa;
create policy "admin_pa_exclui_aprovacao"
on public.aprovacoes_premiacao_pa for delete to authenticated
using (public.eh_admin_pa());

create index if not exists aprovacoes_premiacao_pa_usuario_mes_idx
  on public.aprovacoes_premiacao_pa (usuario_id, mes);
