-- Estrutura do Cálculo PA no mesmo Supabase do Líder Metas.
-- Não altera dados existentes das tabelas atuais.

create table if not exists public.usuarios_pa (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text not null,
  tipo_usuario text not null default 'vendedora' check (tipo_usuario in ('vendedora', 'admin')),
  ativo boolean not null default true,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.dias_pa (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid not null references public.usuarios_pa(id) on delete cascade,
  data date not null,
  situacao text not null default 'trabalhado' check (situacao in ('trabalhado', 'folga', 'falta', 'atestado', 'ferias')),
  observacao text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (usuario_id, data)
);

create table if not exists public.lancamentos_pa (
  id bigint generated by default as identity primary key,
  dia_id uuid not null references public.dias_pa(id) on delete cascade,
  loja_id bigint not null references public.lojas(id),
  vendas integer not null default 0 check (vendas >= 0),
  pecas integer not null default 0 check (pecas >= 0),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  unique (dia_id, loja_id)
);

-- Os usuários que já existem hoje no Líder Metas são administrativos.
insert into public.usuarios_pa (id, nome, tipo_usuario, ativo)
select
  id,
  coalesce(nullif(raw_user_meta_data ->> 'nome', ''), split_part(email, '@', 1)),
  'admin',
  true
from auth.users
on conflict (id) do nothing;

-- Novos usuários criados no Auth entram como vendedora por padrão.
create or replace function public.criar_usuario_pa_automaticamente()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.usuarios_pa (id, nome, tipo_usuario, ativo)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'nome', ''), split_part(new.email, '@', 1)),
    'vendedora',
    true
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists auth_usuario_pa_criado on auth.users;
create trigger auth_usuario_pa_criado
after insert on auth.users
for each row execute function public.criar_usuario_pa_automaticamente();

create or replace function public.eh_admin_pa()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.usuarios_pa
    where id = auth.uid()
      and tipo_usuario = 'admin'
      and ativo = true
  );
$$;

revoke all on function public.eh_admin_pa() from public;
grant execute on function public.eh_admin_pa() to authenticated;

alter table public.usuarios_pa enable row level security;
alter table public.dias_pa enable row level security;
alter table public.lancamentos_pa enable row level security;

-- Perfil: cada usuário vê o próprio registro; admin vê e administra todos.
drop policy if exists "usuario_pa_le_proprio_perfil" on public.usuarios_pa;
create policy "usuario_pa_le_proprio_perfil"
on public.usuarios_pa for select to authenticated
using (id = auth.uid() or public.eh_admin_pa());

drop policy if exists "admin_pa_atualiza_perfis" on public.usuarios_pa;
create policy "admin_pa_atualiza_perfis"
on public.usuarios_pa for update to authenticated
using (public.eh_admin_pa())
with check (public.eh_admin_pa());

-- Dias: vendedora manipula somente os próprios; admin pode consultar todos.
drop policy if exists "usuario_pa_le_dias" on public.dias_pa;
create policy "usuario_pa_le_dias"
on public.dias_pa for select to authenticated
using (usuario_id = auth.uid() or public.eh_admin_pa());

drop policy if exists "usuario_pa_insere_dias" on public.dias_pa;
create policy "usuario_pa_insere_dias"
on public.dias_pa for insert to authenticated
with check (usuario_id = auth.uid() or public.eh_admin_pa());

drop policy if exists "usuario_pa_atualiza_dias" on public.dias_pa;
create policy "usuario_pa_atualiza_dias"
on public.dias_pa for update to authenticated
using (usuario_id = auth.uid() or public.eh_admin_pa())
with check (usuario_id = auth.uid() or public.eh_admin_pa());

drop policy if exists "usuario_pa_exclui_dias" on public.dias_pa;
create policy "usuario_pa_exclui_dias"
on public.dias_pa for delete to authenticated
using (usuario_id = auth.uid() or public.eh_admin_pa());

-- Lançamentos por loja herdam a propriedade do dia.
drop policy if exists "usuario_pa_le_lancamentos" on public.lancamentos_pa;
create policy "usuario_pa_le_lancamentos"
on public.lancamentos_pa for select to authenticated
using (
  public.eh_admin_pa()
  or exists (
    select 1 from public.dias_pa d
    where d.id = dia_id and d.usuario_id = auth.uid()
  )
);

drop policy if exists "usuario_pa_insere_lancamentos" on public.lancamentos_pa;
create policy "usuario_pa_insere_lancamentos"
on public.lancamentos_pa for insert to authenticated
with check (
  public.eh_admin_pa()
  or exists (
    select 1 from public.dias_pa d
    where d.id = dia_id and d.usuario_id = auth.uid()
  )
);

drop policy if exists "usuario_pa_atualiza_lancamentos" on public.lancamentos_pa;
create policy "usuario_pa_atualiza_lancamentos"
on public.lancamentos_pa for update to authenticated
using (
  public.eh_admin_pa()
  or exists (
    select 1 from public.dias_pa d
    where d.id = dia_id and d.usuario_id = auth.uid()
  )
)
with check (
  public.eh_admin_pa()
  or exists (
    select 1 from public.dias_pa d
    where d.id = dia_id and d.usuario_id = auth.uid()
  )
);

drop policy if exists "usuario_pa_exclui_lancamentos" on public.lancamentos_pa;
create policy "usuario_pa_exclui_lancamentos"
on public.lancamentos_pa for delete to authenticated
using (
  public.eh_admin_pa()
  or exists (
    select 1 from public.dias_pa d
    where d.id = dia_id and d.usuario_id = auth.uid()
  )
);

create index if not exists dias_pa_usuario_data_idx on public.dias_pa (usuario_id, data);
create index if not exists lancamentos_pa_dia_idx on public.lancamentos_pa (dia_id);
create index if not exists lancamentos_pa_loja_idx on public.lancamentos_pa (loja_id);
